import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><div className="bg-gray-900 min-h-screen flex text-white  bg-[url('/chrome-gate.jpeg')] bg-center bg-no-repeat">{children}</div></body>
    </html>
  );
}
